[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
basic_5 = "Hp6LF3LrgtHLY5jSCkE6uTo1ToifGfNxuKcrpTx39gmQ"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"